trigger: none

pool: dev-agent-001
  
stages:
- stage: build
  jobs:
  - job: build
    steps:

    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'

    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/environment/Dev'
        backendServiceArm: 'bittubhaiya_service_connection'
        backendAzureRmStorageAccountName: 'testrg0002storageaccount'
        backendAzureRmContainerName: 'backendcontainer'
        backendAzureRmKey: 'dev.terraform.tfstate'

    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/environment/Dev'
        environmentServiceNameAzureRM: 'bittubhaiya_service_connection'


- stage: scanning  
  jobs:
    - job: scanning
      steps:
      
      - task: trivy@2
        inputs:
          version: 'latest'
          type: 'repository'
          target: '$(System.DefaultWorkingDirectory)/environment/Dev'

- stage: validation
  pool: server
  jobs:

    - job: validation

      steps:
      - task: ManualValidation@1
        inputs:
          notifyUsers: 'umesh9315116846@gmail.com'



- stage: apply 
  jobs:
    - job: apply
      steps:
      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'apply'
          workingDirectory: '$(System.DefaultWorkingDirectory)/environment/Dev'
          environmentServiceNameAzureRM: 'bittubhaiya_service_connection'

