trigger: none

pool: dev-agent-001
  
stages:
- stage: build
  jobs:
  - job: build
    steps:
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/environment/Dev'
        backendServiceArm: 'devserviceconnection001'
        backendAzureRmStorageAccountName: 'testrg0001storageaccount'
        backendAzureRmContainerName: 'backendcontainer'
        backendAzureRmKey: 'dev.terraform.tfstate'

  - job: plan
    steps:
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/environment/Dev'
        commandOptions: 'plan'
        environmentServiceNameAzureRM: 'devserviceconnection001'
        