trigger: none

pool: dev-agent-001
  
stages:
- stage: build
  jobs:
  - job: build
    steps:

    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'

    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/environment/Dev'
        backendServiceArm: 'bittubhaiya_service_connection'
        backendAzureRmStorageAccountName: 'testrg0002storageaccount'
        backendAzureRmContainerName: 'backendcontainer'
        backendAzureRmKey: 'dev.terraform.tfstate'

    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/environment/Dev'
        environmentServiceNameAzureRM: 'bittubhaiya_service_connection'

- stage: security_scan
  jobs:
  - job: tfsec_scan
    
    steps:
    - script: |
        sudo wget https://github.com/aquasecurity/tfsec/releases/latest/download/tfsec-linux-amd64 -O /usr/local/bin/tfsec
        sudo chmod +x /usr/local/bin/tfsec
        tfsec --format junit --out tfsec.xml
      displayName: "Run tfsec"

    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: 'tfsec.xml'